"""Vendored/generated subtree classifier (F-R9).

bob's C++ source discovery is a whole-repo ``rglob`` for ``*.cpp``/``*.hpp``/
``*.h``/``*.c`` excluding only ``build`` and ``.git``.  On large repos (e.g.
RCCL) that sweeps in git submodules, third-party/vendored dependencies, and
CMake/hipify-generated sources.  Those nodes inflate the index, misdirect the
localizer, and let the BF-7 patch scope-guard "allow" edits to code that will
be regenerated or overwritten.

This module classifies each indexed path as one of:

* ``source``    — first-party, editable source.
* ``vendored``  — third-party code (git submodules, FetchContent/ExternalProject
                  checkouts, install/vendored directories).  Never edit.
* ``generated`` — machine-generated output (files under the build tree, ``.h``
                  outputs derived from a sibling ``.h.in`` template, hipify
                  outputs, or files carrying a ``DO-NOT-EDIT`` / ``@generated``
                  marker).  Edit the true source instead.

The classification is persisted in ``survey.db`` keyed by ``(path, sha)`` so it
is computed once per content revision.

Downstream:
* the localizer down-ranks or excludes ``vendored``/``generated`` nodes;
* the scope-guard hard-refuses any diff-plan touching such a path and points the
  edit at the true source (the ``.in`` template or the pre-hipify source).
"""

from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Optional

__all__ = [
    "SubtreeClassification",
    "SOURCE",
    "VENDORED",
    "GENERATED",
    "classify_subtree",
    "classify_subtrees",
    "persist_classification",
    "load_classification",
    "parse_gitmodules",
]

SOURCE = "source"
VENDORED = "vendored"
GENERATED = "generated"

_VALID_KINDS = frozenset({SOURCE, VENDORED, GENERATED})

# Directory names that conventionally hold third-party / vendored code.
_DEFAULT_VENDORED_DIRS = frozenset({
    "third_party", "third-party", "thirdparty",
    "vendor", "vendored", "external", "externals",
    "extern", "deps", "_deps", "subprojects",
    "contrib", "install",
})

# Directory names that conventionally hold generated / build output.
_DEFAULT_BUILD_DIRS = frozenset({
    "build", "_build", "cmake-build-debug", "cmake-build-release",
    "out", "generated", "gen",
})

# Content markers that flag a file as machine-generated.  Matched
# case-insensitively against the first chunk of the file.
_GENERATED_MARKERS = (
    "@generated",
    "do-not-edit",
    "do not edit",
    "automatically generated",
    "autogenerated",
    "this file is generated",
    "generated by the hipify",
)

_GENERATED_MARKER_RE = re.compile(
    "|".join(re.escape(m) for m in _GENERATED_MARKERS),
    re.IGNORECASE,
)

# How many bytes at the head of a file to scan for a generated-marker.
_MARKER_SCAN_BYTES = 4096


@dataclass(frozen=True)
class SubtreeClassification:
    """Result of classifying a single indexed path.

    Attributes:
        path:   Repo-relative path (POSIX form) that was classified.
        kind:   One of :data:`SOURCE`, :data:`VENDORED`, :data:`GENERATED`.
        reason: Short human-readable justification for the classification.
    """

    path: str
    kind: str
    reason: str

    @property
    def is_editable(self) -> bool:
        """True only for first-party source that the patcher may edit."""
        return self.kind == SOURCE


def _normalize_rel(path: Any) -> str:
    """Coerce *path* to a normalized POSIX-relative string.

    Raises:
        ValueError: if *path* is not a str/Path, is empty, or is whitespace-only.
    """
    if path is None:
        raise ValueError("path must not be None")
    if isinstance(path, Path):
        text = path.as_posix()
    elif isinstance(path, str):
        text = path
    else:
        raise ValueError(f"path must be a str or Path, got {type(path).__name__}")

    text = text.strip()
    if not text:
        raise ValueError("path must be a non-empty string")

    # Normalize separators and strip a leading "./" so component matching is stable.
    posix = PurePosixPath(text.replace("\\", "/"))
    parts = [p for p in posix.parts if p not in ("", ".")]
    if not parts:
        raise ValueError(f"path {text!r} has no path components")
    return "/".join(parts)


def parse_gitmodules(gitmodules_text: Optional[str]) -> list[str]:
    """Extract submodule ``path = ...`` entries from ``.gitmodules`` text.

    Returns an empty list for ``None`` or empty input (boundary-safe).
    """
    if not gitmodules_text:
        return []
    paths: list[str] = []
    for line in gitmodules_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("path") and "=" in stripped:
            _, _, value = stripped.partition("=")
            value = value.strip()
            if value:
                paths.append(value.replace("\\", "/").strip("/"))
    return paths


def _under_any(parts: tuple[str, ...], prefixes: Iterable[str]) -> Optional[str]:
    """Return the matching prefix if *parts* lies under one of *prefixes*."""
    for prefix in prefixes:
        pref_parts = tuple(p for p in prefix.replace("\\", "/").strip("/").split("/") if p and p != ".")
        if not pref_parts:
            continue
        if len(parts) >= len(pref_parts) and parts[: len(pref_parts)] == pref_parts:
            return prefix
    return None


def _has_component(parts: tuple[str, ...], names: Iterable[str]) -> Optional[str]:
    """Return the first path component that is a member of *names*."""
    nameset = set(names)
    for part in parts:
        if part in nameset:
            return part
    return None


def classify_subtree(
    path: Any,
    *,
    workspace: Optional[Any] = None,
    submodule_paths: Optional[Iterable[str]] = None,
    vendored_dirs: Optional[Iterable[str]] = None,
    build_dirs: Optional[Iterable[str]] = None,
    content: Optional[str] = None,
    sibling_names: Optional[Iterable[str]] = None,
) -> SubtreeClassification:
    """Classify a single indexed *path* as source / vendored / generated.

    Args:
        path:            Repo-relative path (str or Path).  Absolute paths are
                         made relative to *workspace* when possible.
        workspace:       Optional repo root; used to relativize *path* and to
                         read file content / detect ``.in`` siblings when
                         *content*/*sibling_names* are not supplied.
        submodule_paths: Paths from ``.gitmodules`` (git submodules → vendored).
        vendored_dirs:   Extra directory prefixes/names treated as vendored
                         (e.g. CMake ``_deps``, ``ExternalProject`` install
                         dirs).  Merged with sane defaults.
        build_dirs:      Extra directory prefixes/names treated as build output
                         (→ generated).  Merged with sane defaults.
        content:         File content to scan for ``@generated`` / ``DO-NOT-EDIT``
                         markers.  If omitted and *workspace* is given, the file
                         is read from disk.
        sibling_names:   Names of files that live beside *path* (used to detect a
                         ``foo.h`` generated from a ``foo.h.in`` template).  If
                         omitted and *workspace* is given, the directory is listed.

    Returns:
        A :class:`SubtreeClassification`.

    Raises:
        ValueError: if *path* is not a non-empty str/Path.
    """
    rel = _normalize_rel(_relativize(path, workspace))
    parts = tuple(rel.split("/"))

    # --- vendored: git submodules -----------------------------------------
    if submodule_paths:
        match = _under_any(parts, submodule_paths)
        if match:
            return SubtreeClassification(rel, VENDORED, f"git submodule: {match}")

    # --- vendored: third-party / external directory prefixes --------------
    vendored = set(_DEFAULT_VENDORED_DIRS)
    if vendored_dirs:
        vendored.update(v.strip("/") for v in vendored_dirs if v and v.strip("/"))
    # Prefix match first (handles multi-segment dirs like "build/_deps").
    prefix_match = _under_any(parts, (v for v in vendored if "/" in v))
    if prefix_match:
        return SubtreeClassification(rel, VENDORED, f"vendored dir: {prefix_match}")
    comp = _has_component(parts[:-1], (v for v in vendored if "/" not in v))
    if comp:
        return SubtreeClassification(rel, VENDORED, f"vendored dir: {comp}")

    # --- generated: build tree --------------------------------------------
    build = set(_DEFAULT_BUILD_DIRS)
    if build_dirs:
        build.update(b.strip("/") for b in build_dirs if b and b.strip("/"))
    build_prefix = _under_any(parts, (b for b in build if "/" in b))
    if build_prefix:
        return SubtreeClassification(rel, GENERATED, f"build tree: {build_prefix}")
    build_comp = _has_component(parts, (b for b in build if "/" not in b))
    if build_comp:
        return SubtreeClassification(rel, GENERATED, f"build tree: {build_comp}")

    name = parts[-1]

    # --- generated: a ".in" template is itself editable source ------------
    if name.endswith(".in"):
        return SubtreeClassification(rel, SOURCE, "configure-time template (.in)")

    # --- generated: output derived from a sibling ".in" template ----------
    siblings = _resolve_siblings(rel, workspace, sibling_names)
    if siblings and f"{name}.in" in siblings:
        return SubtreeClassification(
            rel, GENERATED, f"derived from template {name}.in"
        )

    # --- generated: content markers ---------------------------------------
    text = _resolve_content(rel, workspace, content)
    if text and _GENERATED_MARKER_RE.search(text[:_MARKER_SCAN_BYTES]):
        return SubtreeClassification(rel, GENERATED, "generated-marker in header")

    return SubtreeClassification(rel, SOURCE, "first-party source")


def classify_subtrees(
    paths: Iterable[Any],
    **kwargs: Any,
) -> list[SubtreeClassification]:
    """Classify many paths.  Empty input returns an empty list (boundary-safe)."""
    if paths is None:
        raise ValueError("paths must not be None")
    return [classify_subtree(p, **kwargs) for p in paths]


def _relativize(path: Any, workspace: Optional[Any]) -> Any:
    """Return *path* relative to *workspace* when it is an absolute descendant."""
    if workspace is None:
        return path
    try:
        p = Path(path)
    except TypeError:
        return path
    if not p.is_absolute():
        return path
    try:
        return p.relative_to(Path(workspace))
    except ValueError:
        return path


def _resolve_siblings(
    rel: str,
    workspace: Optional[Any],
    sibling_names: Optional[Iterable[str]],
) -> set[str]:
    if sibling_names is not None:
        return set(sibling_names)
    if workspace is None:
        return set()
    try:
        parent = (Path(workspace) / rel).parent
        if parent.is_dir():
            return {c.name for c in parent.iterdir()}
    except OSError:
        return set()
    return set()


def _resolve_content(
    rel: str,
    workspace: Optional[Any],
    content: Optional[str],
) -> str:
    if content is not None:
        return content
    if workspace is None:
        return ""
    try:
        f = Path(workspace) / rel
        if f.is_file():
            return f.read_text(errors="replace")
    except OSError:
        return ""
    return ""


# --------------------------------------------------------------------------
# Persistence — survey.db, keyed by (path, sha) so it is computed once per rev.
# --------------------------------------------------------------------------

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS subtree_classification (
    path       TEXT NOT NULL,
    sha        TEXT NOT NULL,
    kind       TEXT NOT NULL,
    reason     TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (path, sha)
);
"""


def _connect(db_path: Any) -> sqlite3.Connection:
    if db_path is None:
        raise ValueError("db_path must not be None")
    if not isinstance(db_path, (str, Path)):
        raise ValueError(
            f"db_path must be a str or Path, got {type(db_path).__name__}"
        )
    conn = sqlite3.connect(str(db_path))
    conn.executescript(_SCHEMA_SQL)
    return conn


def persist_classification(
    db_path: Any,
    classification: Any,
    sha: Optional[str] = None,
) -> int:
    """Persist one or many classifications into ``survey.db``.

    Accepts a single :class:`SubtreeClassification` or an iterable of them.
    Each row is keyed by ``(path, sha)`` and upserted, so re-running with the
    same content is idempotent.

    Args:
        db_path:        Path to the SQLite ``survey.db`` file.
        classification: A single :class:`SubtreeClassification` or an iterable.
                        Passing ``[]`` persists nothing and returns ``0``.
        sha:            Content SHA to key the row by.  A single classification
                        may instead be a ``(SubtreeClassification, sha)`` pair;
                        an iterable may yield such pairs.

    Returns:
        The number of rows written.

    Raises:
        ValueError: for a missing/invalid ``db_path`` or a classification that
                    is neither a :class:`SubtreeClassification` nor a valid
                    ``(classification, sha)`` pair, or one carrying an unknown
                    ``kind``.
    """
    if classification is None:
        raise ValueError("classification must not be None")

    if isinstance(classification, SubtreeClassification):
        items: list[Any] = [classification]
    else:
        try:
            items = list(classification)
        except TypeError as exc:  # not iterable
            raise ValueError(
                "classification must be a SubtreeClassification or an iterable"
            ) from exc

    rows: list[tuple[str, str, str, str]] = []
    for item in items:
        obj, row_sha = _coerce_item(item, sha)
        rows.append((obj.path, row_sha, obj.kind, obj.reason))

    if not rows:
        return 0

    conn = _connect(db_path)
    try:
        conn.executemany(
            "INSERT INTO subtree_classification (path, sha, kind, reason) "
            "VALUES (?, ?, ?, ?) "
            "ON CONFLICT(path, sha) DO UPDATE SET "
            "kind=excluded.kind, reason=excluded.reason, "
            "updated_at=datetime('now')",
            rows,
        )
        conn.commit()
    finally:
        conn.close()
    return len(rows)


def _coerce_item(item: Any, default_sha: Optional[str]) -> tuple[SubtreeClassification, str]:
    """Normalize a persist item into (classification, sha)."""
    obj = item
    row_sha = default_sha
    if isinstance(item, tuple):
        if len(item) != 2:
            raise ValueError(
                "classification pair must be (SubtreeClassification, sha)"
            )
        obj, row_sha = item

    if not isinstance(obj, SubtreeClassification):
        raise ValueError(
            f"expected SubtreeClassification, got {type(obj).__name__}"
        )
    if obj.kind not in _VALID_KINDS:
        raise ValueError(
            f"invalid kind {obj.kind!r}; must be one of {sorted(_VALID_KINDS)}"
        )
    if not row_sha or not str(row_sha).strip():
        raise ValueError(f"sha required to persist classification for {obj.path!r}")
    return obj, str(row_sha)


def load_classification(
    db_path: Any,
    path: str,
    sha: str,
) -> Optional[SubtreeClassification]:
    """Return the cached classification for ``(path, sha)`` or ``None``.

    Raises:
        ValueError: for an invalid ``db_path`` or an empty ``path``/``sha``.
    """
    rel = _normalize_rel(path)
    if not sha or not str(sha).strip():
        raise ValueError("sha must be a non-empty string")
    conn = _connect(db_path)
    try:
        cur = conn.execute(
            "SELECT path, kind, reason FROM subtree_classification "
            "WHERE path = ? AND sha = ?",
            (rel, str(sha)),
        )
        row = cur.fetchone()
    finally:
        conn.close()
    if row is None:
        return None
    return SubtreeClassification(path=row[0], kind=row[1], reason=row[2])
