"""Tests for bob.subtree_classifier (feature 34bfe912).

Vendored/generated subtree classifier for index and scope-guard.
"""
from __future__ import annotations

import sqlite3
import tempfile
from pathlib import Path

import pytest

from bob.subtree_classifier import (
    GENERATED,
    SOURCE,
    VENDORED,
    SubtreeClassification,
    classify_subtree,
    classify_subtrees,
    load_classification,
    parse_gitmodules,
    persist_classification,
)


# --- classify_subtree: source -------------------------------------------------

def test_first_party_source_is_source():
    c = classify_subtree("src/collectives.cpp")
    assert c.kind == SOURCE
    assert c.is_editable is True


def test_dot_in_template_is_source():
    c = classify_subtree("src/config.h.in")
    assert c.kind == SOURCE


# --- classify_subtree: vendored ----------------------------------------------

def test_git_submodule_is_vendored():
    c = classify_subtree(
        "external/hipify/tool.cpp",
        submodule_paths=["external/hipify"],
    )
    assert c.kind == VENDORED
    assert "submodule" in c.reason


def test_third_party_dir_is_vendored():
    c = classify_subtree("third_party/gtest/gtest.cc")
    assert c.kind == VENDORED


def test_cmake_deps_prefix_is_vendored():
    c = classify_subtree(
        "some/_deps/fmt-src/fmt.cpp",
        vendored_dirs=["some/_deps"],
    )
    assert c.kind == VENDORED


def test_vendor_dir_component_is_vendored():
    c = classify_subtree("vendor/rocm/lib.hpp")
    assert c.kind == VENDORED


# --- classify_subtree: generated ---------------------------------------------

def test_build_tree_is_generated():
    c = classify_subtree("build/CMakeFiles/foo.cpp")
    assert c.kind == GENERATED


def test_derived_from_in_template_is_generated():
    c = classify_subtree(
        "src/config.h",
        sibling_names=["config.h", "config.h.in"],
    )
    assert c.kind == GENERATED
    assert "template" in c.reason


def test_generated_marker_is_generated():
    c = classify_subtree(
        "src/hipified_kernel.cpp",
        content="// @generated by hipify — DO-NOT-EDIT\nint main() {}",
    )
    assert c.kind == GENERATED


def test_do_not_edit_marker_case_insensitive():
    c = classify_subtree(
        "src/gen.cpp",
        content="/* This file is generated. Do Not Edit. */",
    )
    assert c.kind == GENERATED


def test_no_marker_stays_source():
    c = classify_subtree(
        "src/real.cpp",
        content="int main() { return 0; }",
    )
    assert c.kind == SOURCE


# --- precedence ---------------------------------------------------------------

def test_submodule_beats_marker():
    # A vendored submodule file that also happens to look generated → vendored.
    c = classify_subtree(
        "ext/lib.cpp",
        submodule_paths=["ext"],
        content="// @generated",
    )
    assert c.kind == VENDORED


# --- parse_gitmodules ---------------------------------------------------------

def test_parse_gitmodules_extracts_paths():
    text = (
        '[submodule "hipify"]\n'
        "\tpath = external/hipify\n"
        "\turl = https://example/hipify.git\n"
        '[submodule "gtest"]\n'
        "\tpath = third_party/gtest\n"
    )
    assert parse_gitmodules(text) == ["external/hipify", "third_party/gtest"]


def test_parse_gitmodules_empty_returns_empty():
    assert parse_gitmodules("") == []
    assert parse_gitmodules(None) == []


# --- classify_subtrees batch --------------------------------------------------

def test_classify_subtrees_batch():
    results = classify_subtrees(
        ["src/a.cpp", "third_party/b.cpp", "build/c.cpp"],
    )
    assert [r.kind for r in results] == [SOURCE, VENDORED, GENERATED]


# --- workspace-driven ---------------------------------------------------------

def test_classify_reads_content_from_workspace():
    ws = Path(tempfile.mkdtemp())
    (ws / "gen.cpp").write_text("// @generated\nvoid f(){}")
    c = classify_subtree("gen.cpp", workspace=ws)
    assert c.kind == GENERATED


def test_classify_detects_in_sibling_from_workspace():
    ws = Path(tempfile.mkdtemp())
    (ws / "config.h.in").write_text("#define X @X@")
    (ws / "config.h").write_text("#define X 1")
    c = classify_subtree("config.h", workspace=ws)
    assert c.kind == GENERATED


def test_absolute_path_relativized():
    ws = Path(tempfile.mkdtemp())
    (ws / "src").mkdir()
    abs_path = ws / "src" / "real.cpp"
    abs_path.write_text("int x;")
    c = classify_subtree(abs_path, workspace=ws)
    assert c.path == "src/real.cpp"
    assert c.kind == SOURCE


# --- persistence --------------------------------------------------------------

def test_persist_and_load_roundtrip():
    db = Path(tempfile.mkdtemp()) / "survey.db"
    c = SubtreeClassification("third_party/x.cpp", VENDORED, "vendored dir")
    n = persist_classification(db, c, sha="abc123")
    assert n == 1
    loaded = load_classification(db, "third_party/x.cpp", "abc123")
    assert loaded is not None
    assert loaded.kind == VENDORED


def test_persist_many():
    db = Path(tempfile.mkdtemp()) / "survey.db"
    items = [
        (SubtreeClassification("a.cpp", SOURCE, "src"), "s1"),
        (SubtreeClassification("build/b.cpp", GENERATED, "gen"), "s2"),
    ]
    n = persist_classification(db, items)
    assert n == 2
    assert load_classification(db, "a.cpp", "s1").kind == SOURCE
    assert load_classification(db, "build/b.cpp", "s2").kind == GENERATED


def test_persist_idempotent_upsert():
    db = Path(tempfile.mkdtemp()) / "survey.db"
    c = SubtreeClassification("a.cpp", SOURCE, "first")
    persist_classification(db, c, sha="v1")
    # Re-persist same key with a corrected kind → upsert, no duplicate row.
    c2 = SubtreeClassification("a.cpp", VENDORED, "reclassified")
    persist_classification(db, c2, sha="v1")
    conn = sqlite3.connect(str(db))
    try:
        count = conn.execute(
            "SELECT COUNT(*) FROM subtree_classification WHERE path='a.cpp'"
        ).fetchone()[0]
    finally:
        conn.close()
    assert count == 1
    assert load_classification(db, "a.cpp", "v1").kind == VENDORED


def test_load_miss_returns_none():
    db = Path(tempfile.mkdtemp()) / "survey.db"
    assert load_classification(db, "nope.cpp", "sha") is None


def test_persist_computed_once_per_path_sha():
    """Different sha for the same path → two distinct rows (per-revision cache)."""
    db = Path(tempfile.mkdtemp()) / "survey.db"
    persist_classification(db, SubtreeClassification("a.cpp", SOURCE, ""), sha="v1")
    persist_classification(db, SubtreeClassification("a.cpp", GENERATED, ""), sha="v2")
    assert load_classification(db, "a.cpp", "v1").kind == SOURCE
    assert load_classification(db, "a.cpp", "v2").kind == GENERATED


# --- integration: bob.score_gate importable ----------------------------------

def test_score_gate_importable():
    import bob.score_gate  # noqa: F401

    assert hasattr(bob.score_gate, "score_gate_loop")
