"""
Contract Writer — Writes verification tests as real .py files.
================================================================

Replaces the old approach of embedding tests as triple-escaped strings
in JSON. Tests are now proper pytest files in `.bob/contracts/`.

Each contract file includes:
1. Real pytest test functions generated from Claude output
2. Meta-tests that validate the test file itself (self-checking)

Validation pipeline:
1. ast.parse() — syntax check
2. compile() — bytecode compilation check
3. AST analysis — assertion count, no trivial 'assert True'
4. Meta-test execution — pytest -k 'test_meta' on the file
"""

from __future__ import annotations

import ast
import importlib.util
import json
import re
import subprocess
import textwrap
from pathlib import Path
from typing import Any, Optional

from bob.observability.logger import EventType, create_logger


# Template for generated contract files
CONTRACT_FILE_TEMPLATE = '''\
"""
Auto-generated verification contract for {task_id} ({category}).
=================================================================

DO NOT EDIT — these tests are generated during planning and are
immutable. The coding agent must write code that passes them.

Source: {source}
Generated by BOB planning pipeline v2 (contract_writer)
"""

import ast
import sys
from pathlib import Path

import pytest

# ─── Meta-tests (validate the test file itself) ───────────────
# These run BEFORE the actual tests to ensure the contract is non-trivial.

def test_meta_has_real_assertions():
    """Meta: this file must have >= {min_assertions} real assertions."""
    source = Path(__file__).read_text()
    tree = ast.parse(source)
    # Count assertions in non-meta test functions.
    # Counts both `assert` statements AND assertion function calls
    # like np.testing.assert_allclose(), pytest.approx(), etc.
    real_asserts = 0
    for func_node in ast.walk(tree):
        if not isinstance(func_node, ast.FunctionDef):
            continue
        if not func_node.name.startswith("test_"):
            continue
        if func_node.name.startswith("test_meta_"):
            continue
        for child in ast.walk(func_node):
            if isinstance(child, ast.Assert):
                real_asserts += 1
            elif isinstance(child, ast.Call):
                # Count np.testing.assert_*, pytest.raises, etc.
                func = child.func
                if isinstance(func, ast.Attribute) and "assert" in func.attr.lower():
                    real_asserts += 1
    assert real_asserts >= {min_assertions}, (
        f"Contract has only {{real_asserts}} real assertions, need >= {min_assertions}"
    )


def test_meta_no_trivial_assertions():
    """Meta: tests must not just 'assert True' or 'assert 1'."""
    source = Path(__file__).read_text()
    tree = ast.parse(source)
    trivial_count = 0
    for node in ast.walk(tree):
        if isinstance(node, ast.Assert):
            test_val = node.test
            # Check for: assert True, assert 1, assert "string"
            if isinstance(test_val, ast.Constant) and test_val.value in (True, 1, ""):
                trivial_count += 1
    assert trivial_count == 0, (
        f"Found {{trivial_count}} trivial assertions (assert True/1)"
    )


def test_meta_has_test_functions():
    """Meta: file must have >= 2 actual test functions (not meta)."""
    source = Path(__file__).read_text()
    tree = ast.parse(source)
    test_funcs = [
        node for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef)
        and node.name.startswith("test_")
        and not node.name.startswith("test_meta_")
    ]
    assert len(test_funcs) >= 2, (
        f"Contract has only {{len(test_funcs)}} test functions, need >= 2"
    )


def test_meta_no_forbidden_imports():
    """Meta: must not import forbidden libraries."""
    source = Path(__file__).read_text()
    tree = ast.parse(source)
    forbidden = {{{forbidden_imports_set}}}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".")[0]
                assert root not in forbidden, (
                    f"Forbidden import: {{alias.name}}"
                )
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                root = node.module.split(".")[0]
                assert root not in forbidden, (
                    f"Forbidden import: {{node.module}}"
                )


# ─── Actual verification tests ────────────────────────────────

{test_code}
'''


# Prompt for generating pytest-style contracts
CONTRACT_GENERATION_PROMPT = """\
You are a verification test engineer writing pytest test files.

## Task Under Test
**ID:** {task_id}
**Title:** {task_title}
**Description:**
{task_description}

**Acceptance Criteria:**
{acceptance_criteria}

**Expected Outputs:**
{expected_outputs}

## Research / Reference Material
{research_context}

## Workspace
Working directory: {workspace_dir}

## What to Generate

Write Python test functions for the **{category}** category.

{category_guidance}

## Output Format

Output ONLY the Python test function code. No imports (those are in the template).
No class wrappers. Just standalone `def test_...():` functions.

Each function must:
- Have a descriptive name starting with `test_`
- Have a docstring explaining what it tests
- Use real assertions (assert, np.testing.assert_allclose, etc.)
- Be self-contained (import what it needs inside the function body)
- Print 'PASS: <description>' on success

Example:
```python
def test_heisenberg_l2_ground_state():
    \"\"\"Test L=2 Heisenberg chain ground state energy.
    Reference: exact diagonalization gives E_0 = -0.75.
    \"\"\"
    import numpy as np
    from src.mpo_builder import build_heisenberg_mpo

    H = build_heisenberg_mpo(L=2, J=1.0)
    # For L=2 we can diagonalize exactly
    import numpy.linalg as la
    H_dense = H.to_dense()
    eigenvalues = la.eigvalsh(H_dense)
    E0 = eigenvalues[0]

    np.testing.assert_allclose(E0, -0.75, atol=1e-10,
        err_msg="L=2 ground state energy wrong")
    print("PASS: L=2 Heisenberg ground state energy")


def test_heisenberg_l4_ground_state():
    \"\"\"Test L=4 Heisenberg chain.
    Reference: E_0/L ≈ -0.4431 from Bethe ansatz.
    \"\"\"
    import numpy as np
    from src.mpo_builder import build_heisenberg_mpo

    H = build_heisenberg_mpo(L=4, J=1.0)
    H_dense = H.to_dense()
    eigenvalues = np.linalg.eigvalsh(H_dense)
    E0_per_site = eigenvalues[0] / 4

    np.testing.assert_allclose(E0_per_site, -0.4431, atol=1e-3,
        err_msg="L=4 energy per site wrong")
    print("PASS: L=4 Heisenberg ground state energy per site")
```

Generate at least 3 test functions for the {category} category.
Output ONLY the Python code. No markdown fences. No explanation.
"""

# Category-specific guidance
CATEGORY_GUIDANCE = {
    "numerical": """\
**Numerical tests** — Known-answer tests with tight tolerances.

These catch:
- Hardcoded return values
- Wrong algorithms giving wrong numbers
- Off-by-one errors

Requirements:
- Use reference values from research/papers
- Tight tolerances (1e-4 for energies, 1e-6 for norms)
- Test with MULTIPLE inputs (different L, different parameters)
- Include inline computation of reference values where possible
""",
    "algorithmic": """\
**Algorithmic tests** — Verify the METHOD, not just the answer.

These catch:
- Wrapping an existing library instead of implementing
- Copy-pasting reference values
- Trivial implementations

Techniques:
- Dependency blocking: monkey-patch forbidden imports to raise errors
- Differential testing: different inputs MUST give different outputs
- Structural checks: code uses specific algorithmic steps (SVD, etc.)
""",
    "convergence": """\
**Convergence tests** — Verify the algorithm behaves correctly as a PROCESS.

These catch:
- Algorithms converging to wrong values
- Implementations that don't actually iterate
- Hardcoded iteration counts with random noise

Properties:
- Energy decreases with each sweep
- Higher bond dimension → lower energy
- Algorithm reaches stable fixed point
- Monotonic improvement of some metric
""",
}


class ContractWriter:
    """Writes verification contracts as .py files in .bob/contracts/.

    Each contract file is a proper pytest file with:
    - Meta-tests that validate the file itself
    - Real verification test functions
    - Proper imports and structure

    Validation checks:
    1. ast.parse() succeeds (syntax)
    2. compile() succeeds (bytecode)
    3. AST analysis (assertion count, no trivials)
    4. Meta-test execution via pytest (optional)
    """

    def __init__(self, workspace_dir: str, forbidden_imports: set[str] | None = None):
        """Initialize ContractWriter.

        Args:
            workspace_dir: Project workspace directory
            forbidden_imports: Set of import names that must not appear in contracts
                             (e.g., {"quimb"} to prevent wrapping quimb's DMRG)
        """
        self.workspace_dir = workspace_dir
        self.contracts_dir = Path(workspace_dir) / ".bob" / "contracts"
        self.contracts_dir.mkdir(parents=True, exist_ok=True)
        self.forbidden_imports = forbidden_imports or set()
        self.logger = create_logger(
            "contract_writer",
            project_workspace=Path(workspace_dir),
        )

    def write_contract(
        self,
        task_id: str,
        category: str,
        test_code: str,
        source: str = "auto-generated",
        min_assertions: int = 3,
    ) -> Path:
        """Write a contract .py file for a task.

        Args:
            task_id: Task identifier (e.g., "T001")
            category: Test category ("numerical", "algorithmic", "convergence")
            test_code: Raw Python test function code (no file-level boilerplate)
            source: Description of where the test values came from
            min_assertions: Minimum assertion count for meta-test

        Returns:
            Path to the written .py file
        """
        # Sanitize task_id for filename
        safe_id = re.sub(r'[^a-zA-Z0-9_]', '_', task_id)
        safe_cat = re.sub(r'[^a-zA-Z0-9_]', '_', category)
        filename = f"{safe_id}_{safe_cat}.py"
        contract_path = self.contracts_dir / filename

        # Format forbidden imports as a Python set literal
        if self.forbidden_imports:
            forbidden_str = ", ".join(f'"{imp}"' for imp in sorted(self.forbidden_imports))
        else:
            forbidden_str = ""

        # Build the full file content
        content = CONTRACT_FILE_TEMPLATE.format(
            task_id=task_id,
            category=category,
            source=source,
            min_assertions=min_assertions,
            forbidden_imports_set=forbidden_str,
            test_code=test_code,
        )

        contract_path.write_text(content)

        self.logger.info(
            f"Contract written: {contract_path.name}",
            event_type=EventType.DECOMPOSITION_STARTED,
            task_id=task_id,
            category=category,
            path=str(contract_path),
        )

        return contract_path

    def validate_contract(self, contract_path: Path) -> tuple[bool, list[str]]:
        """Validate a contract file using AST + compile + structural analysis.

        Checks:
        1. ast.parse() succeeds
        2. compile() succeeds
        3. Has enough real assertions (>=3)
        4. No trivial 'assert True' assertions
        5. Has enough test functions (>=2)
        6. No forbidden imports
        7. Einsum string validation (if numpy used)

        Args:
            contract_path: Path to the .py contract file

        Returns:
            Tuple of (is_valid, list_of_errors)
        """
        errors: list[str] = []
        source = contract_path.read_text()

        # Check 1: AST parse
        try:
            tree = ast.parse(source)
        except SyntaxError as e:
            errors.append(f"Syntax error at line {e.lineno}: {e.msg}")
            return False, errors

        # Check 2: Compile
        try:
            compile(source, str(contract_path), "exec")
        except SyntaxError as e:
            errors.append(f"Compilation error: {e.msg}")
            return False, errors

        # Check 3: Count real assertions (excluding meta-tests)
        real_asserts = self._count_real_assertions(tree)
        if real_asserts < 3:
            errors.append(
                f"Only {real_asserts} real assertions found (need >= 3). "
                f"Tests may be too superficial."
            )

        # Check 4: Detect trivial assertions
        trivial_count = self._count_trivial_assertions(tree)
        if trivial_count > 0:
            errors.append(
                f"Found {trivial_count} trivial assertion(s) "
                f"(assert True, assert 1, etc.)"
            )

        # Check 5: Count test functions (excluding meta)
        test_funcs = self._count_test_functions(tree)
        if test_funcs < 2:
            errors.append(
                f"Only {test_funcs} test function(s) found (need >= 2)"
            )

        # Check 6: Check for forbidden imports
        forbidden_found = self._check_forbidden_imports(tree)
        for imp in forbidden_found:
            errors.append(f"Forbidden import found: {imp}")

        # Check 7: Validate einsum strings
        einsum_errors = self._validate_einsum_strings(tree)
        errors.extend(einsum_errors)

        is_valid = len(errors) == 0

        if not is_valid:
            self.logger.info(
                f"Contract validation failed: {contract_path.name} "
                f"({len(errors)} errors)",
                event_type=EventType.DECOMPOSITION_COMPLETED,
                path=str(contract_path),
                errors=errors,
                valid=False,
            )

        return is_valid, errors

    def validate_and_fix(
        self, contract_path: Path, max_attempts: int = 3
    ) -> tuple[bool, list[str]]:
        """Validate a contract, attempting automatic fixes for common issues.

        Currently fixes:
        - Missing imports (adds them)
        - Indentation issues (reformats)

        Args:
            contract_path: Path to the .py contract file
            max_attempts: Max fix attempts

        Returns:
            Tuple of (is_valid, remaining_errors)
        """
        for attempt in range(max_attempts):
            is_valid, errors = self.validate_contract(contract_path)
            if is_valid:
                return True, []

            # Check if errors are auto-fixable
            fixable = [e for e in errors if self._is_fixable_error(e)]
            if not fixable:
                return False, errors

            # Apply fixes
            source = contract_path.read_text()
            source = self._apply_fixes(source, fixable)
            contract_path.write_text(source)

        return self.validate_contract(contract_path)

    def run_meta_tests(self, contract_path: Path, timeout: int = 30) -> tuple[bool, str]:
        """Run only the meta-tests in a contract file.

        Uses pytest -k 'test_meta' to run self-checking meta-tests.
        These validate the contract structure without needing the
        actual implementation code.

        Args:
            contract_path: Path to the .py contract file
            timeout: Timeout in seconds

        Returns:
            Tuple of (passed, output)
        """
        try:
            result = subprocess.run(
                [
                    "python", "-m", "pytest",
                    str(contract_path),
                    "-k", "test_meta",
                    "-v", "--tb=short",
                    "--no-header",
                ],
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=self.workspace_dir,
                env={
                    **dict(__import__("os").environ),
                    "PYTHONDONTWRITEBYTECODE": "1",
                },
            )
            passed = result.returncode == 0
            output = result.stdout + result.stderr
            return passed, output
        except subprocess.TimeoutExpired:
            return False, f"Meta-tests timed out after {timeout}s"
        except FileNotFoundError:
            return False, "pytest not found — install with: pip install pytest"

    def list_contracts(self, task_id: str | None = None) -> list[Path]:
        """List contract files, optionally filtered by task_id.

        Args:
            task_id: If provided, only return contracts for this task

        Returns:
            List of contract file paths
        """
        if task_id:
            safe_id = re.sub(r'[^a-zA-Z0-9_]', '_', task_id)
            return sorted(self.contracts_dir.glob(f"{safe_id}_*.py"))
        return sorted(self.contracts_dir.glob("*.py"))

    def get_contract_summary(self, contract_path: Path) -> dict[str, Any]:
        """Get a summary of a contract file's contents.

        Returns:
            Dict with test_count, assertion_count, categories, etc.
        """
        source = contract_path.read_text()
        try:
            tree = ast.parse(source)
        except SyntaxError:
            return {"error": "syntax error", "valid": False}

        test_funcs = []
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
                is_meta = node.name.startswith("test_meta_")
                test_funcs.append({
                    "name": node.name,
                    "is_meta": is_meta,
                    "line": node.lineno,
                    "docstring": ast.get_docstring(node) or "",
                })

        return {
            "path": str(contract_path),
            "filename": contract_path.name,
            "total_tests": len(test_funcs),
            "meta_tests": sum(1 for t in test_funcs if t["is_meta"]),
            "real_tests": sum(1 for t in test_funcs if not t["is_meta"]),
            "assertions": self._count_real_assertions(tree),
            "tests": test_funcs,
            "valid": True,
        }

    # ------------------------------------------------------------------
    # Static helpers for converting old-style tests to contracts
    # ------------------------------------------------------------------

    @staticmethod
    def convert_bash_test_to_python(bash_command: str) -> str | None:
        """Attempt to extract Python code from a bash test command.

        Handles patterns like:
            cd /path && python -c "import X; assert Y; print('PASS')"

        Returns:
            Python code string, or None if not convertible
        """
        # Match: python -c "..." or python3 -c "..."
        match = re.search(
            r'python[3]?\s+-c\s+["\'](.+?)["\'](?:\s|$)',
            bash_command,
            re.DOTALL,
        )
        if not match:
            return None

        code = match.group(1)
        # Unescape common patterns
        code = code.replace("\\n", "\n")
        code = code.replace('\\"', '"')
        code = code.replace("\\'", "'")
        code = code.replace("\\\\", "\\")

        # Validate it's parseable Python
        try:
            ast.parse(code)
        except SyntaxError:
            return None

        return code

    @staticmethod
    def convert_old_tests_to_contract_code(
        tests: list[dict], category: str
    ) -> str:
        """Convert old-style test dicts to pytest function code.

        Takes the old format:
            [{"name": "test_name", "command": "cd ... && python -c '...'"}]

        Returns Python code with proper test functions.
        """
        functions = []

        for i, test in enumerate(tests):
            name = test.get("name", f"{category}_test_{i}")
            # Sanitize function name
            func_name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
            if not func_name.startswith("test_"):
                func_name = f"test_{func_name}"

            command = test.get("command", "")
            source_note = test.get("source", "auto-converted from bash")

            # Try to extract Python code from bash command
            python_code = ContractWriter.convert_bash_test_to_python(command)

            if python_code:
                # Indent the code as function body
                indented = textwrap.indent(python_code.strip(), "    ")
                functions.append(
                    f'def {func_name}():\n'
                    f'    """Converted test: {source_note}"""\n'
                    f'{indented}\n'
                )
            else:
                # Can't convert — wrap as subprocess call
                escaped_cmd = command.replace("\\", "\\\\").replace('"', '\\"')
                functions.append(
                    f'def {func_name}():\n'
                    f'    """Converted test (subprocess): {source_note}"""\n'
                    f'    import subprocess\n'
                    f'    result = subprocess.run(\n'
                    f'        [{repr(command)}],\n'
                    f'        shell=True, capture_output=True, text=True,\n'
                    f'        timeout=120,\n'
                    f'    )\n'
                    f'    assert result.returncode == 0, (\n'
                    f'        f"Test failed with exit code {{result.returncode}}:\\n"\n'
                    f'        f"stdout: {{result.stdout[:500]}}\\n"\n'
                    f'        f"stderr: {{result.stderr[:500]}}"\n'
                    f'    )\n'
                    f'    print("PASS: {name}")\n'
                )

        return "\n\n".join(functions)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _count_real_assertions(self, tree: ast.AST) -> int:
        """Count assertions NOT inside meta-test functions."""
        count = 0
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                if node.name.startswith("test_meta_"):
                    continue  # Skip meta-test bodies
                # Count asserts in this function
                for child in ast.walk(node):
                    if isinstance(child, ast.Assert):
                        count += 1
                    # Also count np.testing.assert_* calls
                    elif isinstance(child, ast.Call):
                        func = child.func
                        if isinstance(func, ast.Attribute):
                            if "assert" in func.attr.lower():
                                count += 1
        return count

    def _count_trivial_assertions(self, tree: ast.AST) -> int:
        """Count 'assert True', 'assert 1', etc. outside meta-tests."""
        count = 0
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                if node.name.startswith("test_meta_"):
                    continue
                for child in ast.walk(node):
                    if isinstance(child, ast.Assert):
                        val = child.test
                        if isinstance(val, ast.Constant) and val.value in (True, 1):
                            count += 1
        return count

    def _count_test_functions(self, tree: ast.AST) -> int:
        """Count test functions excluding meta-tests."""
        return sum(
            1
            for node in ast.walk(tree)
            if isinstance(node, ast.FunctionDef)
            and node.name.startswith("test_")
            and not node.name.startswith("test_meta_")
        )

    def _check_forbidden_imports(self, tree: ast.AST) -> list[str]:
        """Find any forbidden imports in the AST."""
        found = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    root = alias.name.split(".")[0]
                    if root in self.forbidden_imports:
                        found.append(alias.name)
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    root = node.module.split(".")[0]
                    if root in self.forbidden_imports:
                        found.append(node.module)
        return found

    def _validate_einsum_strings(self, tree: ast.AST) -> list[str]:
        """Find and validate numpy einsum subscript strings.

        Checks that output indices are a subset of input indices.
        """
        errors = []
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            # Match np.einsum(...) or numpy.einsum(...)
            func = node.func
            is_einsum = False
            if isinstance(func, ast.Attribute) and func.attr == "einsum":
                is_einsum = True
            if not is_einsum:
                continue

            # First arg should be a string constant
            if not node.args:
                continue
            subscript_node = node.args[0]
            if not isinstance(subscript_node, ast.Constant):
                continue
            subscript = subscript_node.value
            if not isinstance(subscript, str):
                continue

            # Parse einsum subscript: "ij,jk->ik"
            if "->" not in subscript:
                continue  # Implicit output — skip

            parts = subscript.split("->")
            if len(parts) != 2:
                errors.append(f"Malformed einsum subscript: {subscript!r}")
                continue

            input_part, output_part = parts
            input_chars = set(c for c in input_part if c.isalpha())
            output_chars = set(c for c in output_part if c.isalpha())

            invalid = output_chars - input_chars
            if invalid:
                errors.append(
                    f"Einsum output chars {invalid} not in inputs: {subscript!r}"
                )

        return errors

    @staticmethod
    def _is_fixable_error(error: str) -> bool:
        """Check if an error can be auto-fixed."""
        # Currently no auto-fixes implemented — placeholder for future
        return False

    @staticmethod
    def _apply_fixes(source: str, errors: list[str]) -> str:
        """Apply automatic fixes to contract source code."""
        # Placeholder — future auto-fixes go here
        return source
