"""Slopsquatting local-module whitelist for the bob security scanner.

The main security_scan slopsquatting check queries PyPI for every import it
finds. This false-positive gate prevents that check from flagging imports that
resolve to modules *already present in the local source tree* (e.g. files
generated by bob itself or first-party sub-modules under src/bob/).

Public API
----------
is_local_module(path)
    Return True when *path* points to a recognised local Python module file or
    a package directory (directory containing __init__.py).

find_local_modules(workspace)
    Walk ``workspace/src/bob/`` and return the set of top-level module names
    that live there. Raises FileNotFoundError when ``src/bob/`` is absent.

check_imports_with_local_whitelist(import_names, whitelist)
    Filter *import_names* by removing any name that appears in *whitelist*.
    Names that survive are suitable candidates for a PyPI existence probe.
"""

from __future__ import annotations

from pathlib import Path


def is_local_module(path: Path) -> bool:
    """Return True if *path* is a local Python module or package.

    A path is considered a local module when:
    - It is an existing ``.py`` file (any name), OR
    - It is an existing directory that contains an ``__init__.py`` file
      (i.e. it is a Python package).

    All other inputs return False.
    """
    if not path.exists():
        return False
    if path.is_file():
        return path.suffix == ".py"
    if path.is_dir():
        return (path / "__init__.py").exists()
    return False


def find_local_modules(workspace: Path) -> set[str]:
    """Return top-level module names found under ``workspace/src/bob/``.

    Walks the immediate children of ``src/bob/`` and collects:
    - The stem of every ``<name>.py`` file (excluding ``__init__``).
    - The name of every directory that contains ``__init__.py``.

    Raises:
        FileNotFoundError: when ``workspace/src/bob/`` does not exist.
    """
    src_bob = workspace / "src" / "bob"
    if not src_bob.exists():
        raise FileNotFoundError(
            f"Local module tree not found: {src_bob} does not exist. "
            "Cannot build local-module whitelist without the source tree."
        )

    modules: set[str] = set()
    for child in src_bob.iterdir():
        if child.is_file() and child.suffix == ".py" and child.stem != "__init__":
            modules.add(child.stem)
        elif child.is_dir() and (child / "__init__.py").exists():
            modules.add(child.name)
    return modules


def check_imports_with_local_whitelist(
    import_names: list[str],
    whitelist: set[str],
) -> list[str]:
    """Filter *import_names* by removing names present in *whitelist*.

    Names that survive the filter are not local modules and are therefore
    appropriate candidates for a PyPI existence probe.

    Args:
        import_names: Ordered list of top-level import names to check.
        whitelist: Set of local module names that must be excluded from
            the PyPI probe.

    Returns:
        A list of import names with all whitelisted names removed, in the
        same order as the input.
    """
    if not whitelist:
        return list(import_names)
    return [name for name in import_names if name not in whitelist]
