"""Test-writer sub-agent — emit one failing pytest per AC before implementer fires.

Inserts between spec-critic (F-R7-450) and the implementer sub-agent.

Given a validated feature spec, ``emit_failing_tests`` writes one
``tests/<feature_id>/test_<ac_id>.py`` per acceptance criterion.  The
implementer receives the spec AND the failing tests; its definition of
done is "all AC-tagged tests now pass".

``verify_bijection`` confirms that the AC↔test mapping is bijective:
every AC has exactly one test file, and every such file maps back to a
declared AC.

``triple_filter`` rejects tests that:
  1. Don't compile (SyntaxError / ImportError at collection time)
  2. Mysteriously pass on stub code (test passes when the module it
     exercises does not exist or raises NotImplementedError)
  3. Fail to raise coverage of the AC-named region (placeholder — full
     AST-coverage integration is out of scope for this module)

Public API::

    from bob.orchestrator.test_writer_agent import (
        emit_failing_tests,
        verify_bijection,
        triple_filter,
    )

Source: Agent 4 §9 + AC-F-TEST-FIRST-CASCADE-1, Agent 2 §AutoUAT,
Agent 3 §predicate_coverage sub-metric.
"""

from __future__ import annotations

import ast
import hashlib
import logging
import re
import subprocess
import sys
import tempfile
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class EmittedTest:
    """Metadata about a single emitted test file."""

    ac_index: int
    ac_id: str          # slugified, e.g. "ac_0", "ac_1"
    ac_text: str
    test_path: Path     # tests/<feature_id>/test_<ac_id>.py
    feature_id: str


@dataclass
class BijectionReport:
    """Result of verify_bijection."""

    is_bijective: bool
    missing_tests: list[str]        # AC IDs with no matching test file
    orphan_tests: list[str]         # test files with no matching AC
    ac_ids: list[str]
    test_paths: list[str]


@dataclass
class FilterResult:
    """Result of triple_filter for one test file."""

    test_path: Path
    ac_id: str
    compiles: bool
    fails_on_stub: bool             # True = correctly fails (desired)
    raises_coverage: bool           # True = passes the coverage heuristic
    accepted: bool                  # True = all three checks passed
    reason: str = ""                # populated when accepted=False


# ---------------------------------------------------------------------------
# AC-ID helpers
# ---------------------------------------------------------------------------

_SAFE_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(text: str, index: int) -> str:
    """Convert AC text to a filesystem-safe slug, fall back to ac_<index>."""
    slug = _SAFE_SLUG_RE.sub("_", text.lower()).strip("_")[:40]
    return slug if slug else f"ac_{index}"


def _ac_id(index: int, ac_text: str) -> str:
    """Return the canonical ac_id for an acceptance criterion."""
    return f"ac_{index}_{_slugify(ac_text, index)}"


# ---------------------------------------------------------------------------
# Template generation
# ---------------------------------------------------------------------------

_TEST_TEMPLATE = textwrap.dedent(
    '''\
    """Failing test for AC-{ac_index}: {ac_text_short}

    This file is generated by the test-writer sub-agent before the
    implementer fires.  It must FAIL before implementation and PASS
    after a correct implementation.

    AC (verbatim): {ac_text}
    Feature-ID:    {feature_id}
    AC-ID:         {ac_id}
    """

    from __future__ import annotations

    import pytest


    class Test{class_name}:
        """Acceptance criterion: {ac_text_short}"""

        def test_{ac_id}_not_yet_implemented(self):
            """RED: this test must fail until the feature is implemented.

            Replace this body with real assertions once the feature exists.
            """
            pytest.fail(
                "AC not yet implemented: {ac_text_short!r} — "
                "replace with real assertions after implementation."
            )
    '''
)


def _class_name(ac_id: str) -> str:
    parts = ac_id.split("_")
    return "".join(p.capitalize() for p in parts if p)


def _render_real_structural_test(
    feature_id: str, ac_index: int, ac_text: str, ac_id: str
) -> str | None:
    """Generate a REAL per-AC test for a structural AC, or None if not structural.

    Structural ACs ("File exists", "Function defined", "Class defined",
    "integration:") fully specify what to check, so the test-writer can emit a
    genuine assertion instead of a RED placeholder. The test fails before
    implementation (file/symbol absent) and passes after — true RED→GREEN — and
    is a durable regression test rather than an unreplaced stub. Non-structural
    ACs return None (caller falls back to the RED stub the implementer must
    flesh out). 2026-06-20 deepen — see draining-vs-correct-implementation.
    """
    import re as _re
    s = ac_text.strip()
    low = s.lower()
    short = s[:72].replace("\n", " ")
    cls = _class_name(ac_id)
    header = (
        f'"""Real structural test for AC-{ac_index}: {short}\n\n'
        f"AC (verbatim): {s}\nFeature-ID: {feature_id}\nAC-ID: {ac_id}\n"
        '"""\nfrom __future__ import annotations\nimport importlib, pathlib\n\n\n'
    )

    # Identifiers/paths are interpolated at GENERATION time into double-quoted
    # literals (they contain no double quotes), and assertion messages are plain
    # (non-f) strings — this avoids nested-quote syntax errors in the emitted file.
    def _ident_ok(x: str) -> bool:
        return bool(_re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.]*", x or ""))

    if low.startswith("file exists:"):
        path = s.split(":", 1)[1].strip().split()[0].lstrip("/")
        if path.startswith("workspace/"):
            path = path[len("workspace/"):]
        if '"' in path or "\n" in path:
            return None
        return header + (
            f"def test_{ac_id}_file_exists():\n"
            f'    p = pathlib.Path("{path}")\n'
            f"    pkg = p.with_suffix('') / '__init__.py' if p.suffix == '.py' else None\n"
            f"    assert p.exists() or (pkg is not None and pkg.exists()), "
            f'"required file missing: {path}"\n'
        )

    if low.startswith("function defined:") or low.startswith("class defined:"):
        dotted = _re.split(r"\s+\(", s.split(":", 1)[1].strip(), maxsplit=1)[0].strip()
        if "." in dotted:
            mod, sym = dotted.rsplit(".", 1)
        else:
            mod, sym = "bob", dotted
        if not (_ident_ok(mod) and _ident_ok(sym)):
            return None
        kind = "class" if low.startswith("class defined:") else "function"
        chk = "isinstance(obj, type)" if kind == "class" else "callable(obj)"
        return header + (
            f"def test_{ac_id}_{kind}_defined():\n"
            f'    m = importlib.import_module("{mod}")\n'
            f'    assert hasattr(m, "{sym}"), "{kind} {sym} not defined in {mod}"\n'
            f'    obj = getattr(m, "{sym}")\n'
            f'    assert {chk}, "{sym} exists but is not a {kind}"\n'
        )

    if low.startswith("integration:"):
        body = s.split(":", 1)[1].strip()
        m = _re.search(r"\b([a-zA-Z_][\w]*(?:\.[a-zA-Z_][\w]*)+)\b", body)
        if m and _ident_ok(m.group(1)):
            mod = m.group(1)
            return header + (
                f"def test_{ac_id}_integration_importable():\n"
                f"    import importlib.util\n"
                f'    assert importlib.util.find_spec("{mod}") is not None, '
                f'"integration target not importable: {mod}"\n'
            )
    return None


def _render_test(feature_id: str, ac_index: int, ac_text: str, ac_id: str) -> str:
    real = _render_real_structural_test(feature_id, ac_index, ac_text, ac_id)
    if real is not None:
        return real
    short = ac_text[:72].replace("\n", " ")
    return _TEST_TEMPLATE.format(
        ac_index=ac_index,
        ac_text=ac_text,
        ac_text_short=short,
        feature_id=feature_id,
        ac_id=ac_id,
        class_name=_class_name(ac_id),
    )


# ---------------------------------------------------------------------------
# Public: emit_failing_tests
# ---------------------------------------------------------------------------


def emit_failing_tests(
    feature_id: str,
    acceptance_criteria: list[str],
    workspace: str | Path | None = None,
) -> list[EmittedTest]:
    """Write one failing pytest file per acceptance criterion.

    Files are placed under ``<workspace>/tests/<feature_id>/test_<ac_id>.py``.
    An ``__init__.py`` is created in the output directory if absent.

    Args:
        feature_id: UUID (or any string) identifying the feature.
        acceptance_criteria: List of AC strings.
        workspace: Root of the project.  Defaults to ``Path.cwd()``.

    Returns:
        List of EmittedTest metadata objects (one per AC).
    """
    root = Path(workspace) if workspace else Path.cwd()
    out_dir = root / "tests" / feature_id
    out_dir.mkdir(parents=True, exist_ok=True)

    init = out_dir / "__init__.py"
    if not init.exists():
        init.write_text("", encoding="utf-8")

    emitted: list[EmittedTest] = []
    for idx, ac_text in enumerate(acceptance_criteria):
        ac_id = _ac_id(idx, ac_text)
        test_path = out_dir / f"test_{ac_id}.py"
        content = _render_test(feature_id, idx, ac_text, ac_id)
        test_path.write_text(content, encoding="utf-8")
        logger.debug("Emitted failing test: %s", test_path)
        emitted.append(
            EmittedTest(
                ac_index=idx,
                ac_id=ac_id,
                ac_text=ac_text,
                test_path=test_path,
                feature_id=feature_id,
            )
        )

    logger.info(
        "emit_failing_tests: wrote %d test file(s) for feature %s",
        len(emitted),
        feature_id[:8],
    )
    return emitted


# ---------------------------------------------------------------------------
# Public: verify_bijection
# ---------------------------------------------------------------------------


def verify_bijection(
    feature_id: str,
    acceptance_criteria: list[str],
    workspace: str | Path | None = None,
) -> BijectionReport:
    """Confirm a bijection between ACs and test files.

    Every AC must have exactly one ``test_<ac_id>.py`` under
    ``tests/<feature_id>/``, and every such file must map back to a
    declared AC.

    Args:
        feature_id: Feature identifier.
        acceptance_criteria: Declared list of AC strings.
        workspace: Project root.  Defaults to ``Path.cwd()``.

    Returns:
        BijectionReport with ``is_bijective=True`` iff no missing or orphan
        tests were found.
    """
    root = Path(workspace) if workspace else Path.cwd()
    out_dir = root / "tests" / feature_id

    expected_ac_ids = [_ac_id(i, ac) for i, ac in enumerate(acceptance_criteria)]

    # Collect test files that match our naming convention
    if out_dir.exists():
        found_files = sorted(p.name for p in out_dir.glob("test_*.py"))
    else:
        found_files = []

    # Build mapping: ac_id -> expected filename
    expected_files = {f"test_{ac_id}.py" for ac_id in expected_ac_ids}

    missing_tests = [
        ac_id for ac_id in expected_ac_ids
        if f"test_{ac_id}.py" not in found_files
    ]
    orphan_tests = [
        fname for fname in found_files
        if fname not in expected_files and fname != "__init__.py"
    ]

    is_bijective = not missing_tests and not orphan_tests

    return BijectionReport(
        is_bijective=is_bijective,
        missing_tests=missing_tests,
        orphan_tests=orphan_tests,
        ac_ids=expected_ac_ids,
        test_paths=[str(out_dir / f"test_{ac_id}.py") for ac_id in expected_ac_ids],
    )


# ---------------------------------------------------------------------------
# Public: triple_filter
# ---------------------------------------------------------------------------


def triple_filter(
    emitted_tests: list[EmittedTest],
    workspace: str | Path | None = None,
) -> list[FilterResult]:
    """Apply the TestGen-LLM triple filter to each emitted test file.

    The three checks:
    1. **Compile**: ``py_compile`` / AST parse succeeds.
    2. **Fails on stub**: Running the test against a minimal stub (i.e. an
       empty temp directory with no source modules) returns non-zero exit code,
       meaning the test is genuinely red when nothing is implemented.
    3. **Raises coverage**: Heuristic — the test imports or references
       at least one symbol that isn't pytest itself, meaning it exercises
       real code rather than being a vacuous no-op.

    Args:
        emitted_tests: List of EmittedTest objects from ``emit_failing_tests``.
        workspace: Project root.  Used to resolve test paths.

    Returns:
        List of FilterResult, one per input test.
    """
    results: list[FilterResult] = []
    for et in emitted_tests:
        path = et.test_path

        # ---- Check 1: compiles ----
        compiles = _check_compiles(path)
        if not compiles:
            results.append(
                FilterResult(
                    test_path=path,
                    ac_id=et.ac_id,
                    compiles=False,
                    fails_on_stub=False,
                    raises_coverage=False,
                    accepted=False,
                    reason="SyntaxError or uncompilable — test rejected",
                )
            )
            continue

        # ---- Check 2: fails on stub ----
        fails_on_stub = _check_fails_on_stub(path)
        if not fails_on_stub:
            results.append(
                FilterResult(
                    test_path=path,
                    ac_id=et.ac_id,
                    compiles=True,
                    fails_on_stub=False,
                    raises_coverage=False,
                    accepted=False,
                    reason="Test passes on stub code — no coverage of AC-named symbol, rejected",
                )
            )
            continue

        # ---- Check 3: raises coverage heuristic ----
        raises_coverage = _check_raises_coverage(path)

        accepted = raises_coverage
        reason = "" if accepted else "Test does not reference any non-pytest symbol — coverage check failed"

        results.append(
            FilterResult(
                test_path=path,
                ac_id=et.ac_id,
                compiles=True,
                fails_on_stub=True,
                raises_coverage=raises_coverage,
                accepted=accepted,
                reason=reason,
            )
        )

    return results


# ---------------------------------------------------------------------------
# Internal helpers for triple_filter
# ---------------------------------------------------------------------------


def _check_compiles(path: Path) -> bool:
    """Return True if the test file parses without SyntaxError."""
    try:
        source = path.read_text(encoding="utf-8")
        ast.parse(source, filename=str(path))
        return True
    except (SyntaxError, UnicodeDecodeError):
        logger.debug("triple_filter compile check failed for %s", path)
        return False


def _check_fails_on_stub(path: Path) -> bool:
    """Return True if running the test in an isolated empty dir exits non-zero.

    Fast-path: uses AST analysis to detect definitively-failing tests (those
    with unconditional ``pytest.fail(...)`` calls) and definitively-passing
    tests (those with only ``assert True`` or bare ``pass`` bodies) without
    spawning a subprocess.  For ambiguous cases, falls back to spawning
    ``python -m pytest <test_file> --tb=no -q`` in a fresh temp directory.
    """
    fast_result = _ast_stub_check(path)
    if fast_result is not None:
        return fast_result

    try:
        with tempfile.TemporaryDirectory() as tmp:
            result = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "pytest",
                    str(path),
                    "--tb=no",
                    "-q",
                    "--no-header",
                ],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=tmp,
            )
            # Non-zero exit code = test failed (as expected for red tests)
            return result.returncode != 0
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        # If we can't run pytest, assume the test is properly failing
        logger.debug("triple_filter stub check could not run pytest for %s", path)
        return True


def _ast_stub_check(path: Path) -> bool | None:
    """AST-based fast-path for _check_fails_on_stub.

    Returns:
        True  — test is definitively red (unconditional pytest.fail call found)
        False — test is definitively green (only assert True / pass bodies)
        None  — ambiguous; caller must spawn subprocess
    """
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
    except (SyntaxError, UnicodeDecodeError):
        return None  # uncompilable; compile check will reject it

    has_pytest_fail = False
    has_only_trivial = True
    imports_stub_sensitive = False  # pathlib/importlib asserts always fail on stubs

    _STUB_SENSITIVE = frozenset({"pathlib", "importlib"})

    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            # pytest.fail(...) or pytest.raises(...) used as a direct call
            if (
                isinstance(func, ast.Attribute)
                and isinstance(func.value, ast.Name)
                and func.value.id == "pytest"
                and func.attr in ("fail", "raises", "warns")
            ):
                has_pytest_fail = True
        elif isinstance(node, ast.Assert):
            # assert True is trivially green; anything else is non-trivial
            if not (isinstance(node.test, ast.Constant) and node.test.value is True):
                has_only_trivial = False
        elif isinstance(node, ast.Raise):
            has_only_trivial = False
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.split(".")[0] in _STUB_SENSITIVE:
                    imports_stub_sensitive = True
        elif isinstance(node, ast.ImportFrom):
            mod = (node.module or "").split(".")[0]
            if mod in _STUB_SENSITIVE:
                imports_stub_sensitive = True

    if has_pytest_fail:
        return True  # definitively failing
    if has_only_trivial:
        # Only assert True / pass — definitively green (passes on stub)
        return False
    if imports_stub_sensitive and not has_only_trivial:
        # Non-trivial assertions checking pathlib.Path.exists() or importlib
        # calls will always fail on a stub (missing files/modules).
        return True
    return None  # ambiguous; let subprocess decide


def _check_raises_coverage(path: Path) -> bool:
    """Heuristic: test references at least one non-pytest import or symbol.

    Parses the AST and looks for:
    - ``import`` or ``from ... import`` of any module other than pytest/builtins
    - Any ``assert`` statement that is not ``assert True``

    This is a coverage *heuristic*, not full instrumented coverage.
    """
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
    except (SyntaxError, UnicodeDecodeError):
        return False

    _STDLIB_ONLY = frozenset({"pytest", "builtins", "__future__", "typing"})

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                top = alias.name.split(".")[0]
                if top not in _STDLIB_ONLY:
                    return True
        elif isinstance(node, ast.ImportFrom):
            mod = (node.module or "").split(".")[0]
            if mod and mod not in _STDLIB_ONLY:
                return True
        elif isinstance(node, ast.Assert):
            # Any non-trivial assertion counts
            if not (
                isinstance(node.test, ast.Constant) and node.test.value is True
            ):
                return True
        elif isinstance(node, ast.Raise):
            # An explicit raise (not bare re-raise) counts as non-trivial
            if node.exc is not None:
                return True

    # Templates emit pytest.fail(...) which counts as exercising pytest — but
    # our template also calls pytest.fail which is a non-trivial assertion
    # equivalent.  Check for pytest.fail or pytest.raises calls.
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name):
                if func.value.id == "pytest" and func.attr in ("fail", "raises", "warns", "approx"):
                    return True

    return False


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Public: emit_failing_test (singular convenience wrapper)
# ---------------------------------------------------------------------------


def emit_failing_test(
    feature_id: str,
    ac_index: int,
    ac_text: str,
    *,
    workspace: "str | Path | None" = None,
) -> EmittedTest:
    """Emit a single failing pytest file for one acceptance criterion.

    Writes ``tests/<feature_id>/test_<ac_id>.py`` (creating intermediate
    directories and ``__init__.py`` as needed).

    Args:
        feature_id: Unique feature identifier (UUID or any filesystem-safe string).
        ac_index: Zero-based index of this AC within the feature's AC list.
        ac_text: The full acceptance criterion text.
        workspace: Project root directory; defaults to ``Path.cwd()``.

    Returns:
        EmittedTest metadata for the written file.

    Raises:
        ValueError: When ``feature_id`` is empty or ``ac_text`` is not a string.
    """
    if not isinstance(feature_id, str) or not feature_id.strip():
        raise ValueError(
            f"feature_id must be a non-empty string, got {feature_id!r}"
        )
    if not isinstance(ac_text, str):
        raise ValueError(
            f"ac_text must be a string, got {type(ac_text).__name__!r}"
        )

    root = Path(workspace) if workspace else Path.cwd()
    out_dir = root / "tests" / feature_id
    out_dir.mkdir(parents=True, exist_ok=True)

    init = out_dir / "__init__.py"
    if not init.exists():
        init.write_text("", encoding="utf-8")

    ac_id = _ac_id(ac_index, ac_text)
    test_path = out_dir / f"test_{ac_id}.py"
    content = _render_test(feature_id, ac_index, ac_text, ac_id)
    test_path.write_text(content, encoding="utf-8")

    return EmittedTest(
        ac_index=ac_index,
        ac_id=ac_id,
        ac_text=ac_text,
        test_path=test_path,
        feature_id=feature_id,
    )


# ---------------------------------------------------------------------------
# Public: generate_failing_tests (AC-required alias with extended return type)
# ---------------------------------------------------------------------------


def generate_failing_tests(
    feature_id: str,
    acceptance_criteria: list[str],
    *,
    workspace: "str | Path | None" = None,
) -> dict[str, Any]:
    """Generate failing tests for each acceptance criterion before implementation.

    Alias for the full test-writer pipeline:
    1. emit_failing_tests — write one test file per AC
    2. triple_filter — reject tests that don't compile, pass on stub, or lack coverage
    3. verify_bijection — confirm AC↔test bijection

    Args:
        feature_id: Unique feature identifier (UUID or slug).
        acceptance_criteria: Ordered list of AC strings for this feature.
        workspace: Project root directory; defaults to ``Path.cwd()``.

    Returns:
        dict with keys:
            emitted: list[EmittedTest]
            filter_results: list[FilterResult]
            bijection: BijectionReport
            gate_passed: bool — True when all triple-filter checks pass and bijection is satisfied

    Raises:
        ValueError: When ``feature_id`` is empty or ``acceptance_criteria`` is not a list.
    """
    if not isinstance(feature_id, str) or not feature_id.strip():
        raise ValueError(f"feature_id must be a non-empty string, got {feature_id!r}")
    if not isinstance(acceptance_criteria, list):
        raise ValueError(
            f"acceptance_criteria must be a list, got {type(acceptance_criteria).__name__!r}"
        )

    emitted: list[EmittedTest] = emit_failing_tests(
        feature_id,
        acceptance_criteria,
        workspace=workspace,
    )

    filter_results: list[FilterResult] = triple_filter(emitted, workspace=workspace)

    bijection: BijectionReport = verify_bijection(
        feature_id,
        acceptance_criteria,
        workspace=workspace,
    )

    all_accepted = all(r.accepted for r in filter_results)
    gate_passed = all_accepted and bijection.is_bijective

    return {
        "emitted": emitted,
        "filter_results": filter_results,
        "bijection": bijection,
        "gate_passed": gate_passed,
    }


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class UncompilableTestError(Exception):
    """Raised by reject_uncompilable when a test file fails py_compile."""


class StubPassError(Exception):
    """Raised by reject_passes_on_stub when a test passes against a stub."""


class NoCoverageUpliftError(Exception):
    """Raised by reject_no_coverage_uplift when a test doesn't cover its AC region."""


# ---------------------------------------------------------------------------
# Public: reject_* convenience wrappers (raising variants of triple_filter)
# ---------------------------------------------------------------------------


def reject_uncompilable(path: "str | Path") -> None:
    """Raise UncompilableTestError if the test file at *path* fails py_compile.

    Passes silently when the file compiles without errors.

    Args:
        path: Path to the test file to validate.

    Raises:
        UncompilableTestError: When the file has a SyntaxError or cannot be parsed.
    """
    import py_compile  # stdlib; import here to keep top-level imports light

    path = Path(path)
    try:
        py_compile.compile(str(path), doraise=True)
    except py_compile.PyCompileError as exc:
        raise UncompilableTestError(
            f"Test file {path} failed py_compile: {exc}"
        ) from exc


def reject_passes_on_stub(path: "str | Path") -> None:
    """Raise StubPassError if the test at *path* passes against an empty stub.

    An empty stub means no source modules are installed — the test is run in
    a fresh temporary directory.  If the test exits 0 (green) under those
    conditions it is not genuinely red and must be rejected.

    Args:
        path: Path to the test file to validate.

    Raises:
        StubPassError: When the test exits 0 against an empty stub environment.
    """
    path = Path(path)
    try:
        with tempfile.TemporaryDirectory() as tmp:
            result = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "pytest",
                    str(path),
                    "--tb=no",
                    "-q",
                    "--no-header",
                ],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=tmp,
            )
            if result.returncode == 0:
                raise StubPassError(
                    f"Test {path} passes against empty stub (exit 0) — "
                    "mysteriously green; test must be genuinely red before implementation."
                )
    except subprocess.TimeoutExpired:
        # A timeout means something is running (not silently passing)
        logger.debug("reject_passes_on_stub: pytest timed out for %s — treating as not-passing", path)


def reject_no_coverage_uplift(path: "str | Path", ac_region: str | None = None) -> None:
    """Raise NoCoverageUpliftError if the test doesn't reference the AC-named region.

    Uses the same heuristic as ``_check_raises_coverage``: the test must import
    at least one non-pytest symbol or contain a non-trivial assertion or
    pytest.fail/raises call.  When *ac_region* is provided the test source is
    additionally scanned for a literal reference to that region string.

    Args:
        path: Path to the test file.
        ac_region: Optional AC-named region (e.g. a module or function name).
                   When given, the test must reference this string somewhere.

    Raises:
        NoCoverageUpliftError: When the test fails the coverage heuristic.
    """
    path = Path(path)
    if not _check_raises_coverage(path):
        raise NoCoverageUpliftError(
            f"Test {path} does not reference any non-pytest symbol — "
            "no coverage uplift of the AC-named region detected."
        )
    if ac_region:
        try:
            source = path.read_text(encoding="utf-8")
        except OSError:
            raise NoCoverageUpliftError(
                f"Test {path} could not be read for AC-region coverage check."
            )
        if ac_region not in source:
            raise NoCoverageUpliftError(
                f"Test {path} does not reference the AC-named region {ac_region!r}."
            )
