#!/usr/bin/env bash
# auto_fix_known_failures.sh — detect and auto-fix (or suggest fixes for) known
# recurring failure patterns in the bob3 build.
#
# Safe auto-fixes:  copy missing reviews/findings.yaml.
# Suggestions only: model-assertion casing, banned-op in specs.
# Idempotent: safe to run multiple times.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GEN_DIR="$(dirname "$SCRIPT_DIR")"
SRC_DIR="$GEN_DIR/src"
TESTS_DIR="$GEN_DIR/tests"
EXAMPLES_DIR="$GEN_DIR/examples"
REVIEWS_DIR="$GEN_DIR/reviews"
SUGGESTED_FIXES="$GEN_DIR/tools/SUGGESTED_FIXES.txt"
CANONICAL_FINDINGS="/home/yelkhamr/dark-factory/bob/reviews/findings.yaml"

log() {
    echo "[$(date '+%Y-%m-%dT%H:%M:%S')] $*"
}

# ── Initialise SUGGESTED_FIXES.txt ───────────────────────────────────────────
{
    echo "# SUGGESTED_FIXES.txt — generated by auto_fix_known_failures.sh"
    echo "# $(date '+%Y-%m-%d %H:%M:%S')"
    echo "# Review each entry and apply manually if appropriate."
    echo ""
} > "$SUGGESTED_FIXES"

FIXES_ADDED=0
append_suggestion() {
    local section="$1"
    local detail="$2"
    echo "## $section" >> "$SUGGESTED_FIXES"
    echo "$detail" >> "$SUGGESTED_FIXES"
    echo "" >> "$SUGGESTED_FIXES"
    FIXES_ADDED=$(( FIXES_ADDED + 1 ))
}

log "=== auto_fix_known_failures.sh start ==="

# ── Pattern 1: Model assertions missing .lower() ─────────────────────────────
# Detect lines like: assert "sonnet" in opts.model  (no .lower() on the model value)
log "PATTERN 1: scanning for model assertions missing .lower() ..."

HITS_MODEL="$(grep -rn \
    -e '"sonnet" in opts\.model[^.]' \
    -e '"opus" in opts\.model[^.]' \
    -e '"haiku" in opts\.model[^.]' \
    -e '"sonnet" in result[^.]' \
    "$TESTS_DIR" "$SRC_DIR" 2>/dev/null || true)"

if [[ -n "$HITS_MODEL" ]]; then
    log "PATTERN 1: found $(echo "$HITS_MODEL" | wc -l) potential issues"
    append_suggestion \
        "Hardcoded model assertions missing .lower()" \
        "$(echo "$HITS_MODEL" | awk -F: '{printf "  %s:%s\n    Fix: change opts.model → opts.model.lower() (or result → result.lower())\n    Line: %s\n\n", $1, $2, $3}')"
else
    log "PATTERN 1: none found"
fi

# ── Pattern 2: Banned ops in acceptance-criteria YAML ────────────────────────
# The ban: acceptance criteria must not use import subprocess, os.system, etc.
log "PATTERN 2: scanning for banned ops in examples/bootstrap_v0*.yaml ..."

BANNED_PATTERNS=(
    'import subprocess'
    'import os'
    'os\.system'
    'subprocess\.run'
    'subprocess\.call'
    'subprocess\.Popen'
)

HITS_BANNED=""
for yaml_file in "$EXAMPLES_DIR"/bootstrap_v0*.yaml; do
    [[ -f "$yaml_file" ]] || continue
    for pat in "${BANNED_PATTERNS[@]}"; do
        MATCH="$(grep -n "$pat" "$yaml_file" 2>/dev/null || true)"
        if [[ -n "$MATCH" ]]; then
            HITS_BANNED+="$yaml_file:"$'\n'"$MATCH"$'\n'
        fi
    done
done

if [[ -n "$HITS_BANNED" ]]; then
    COUNT="$(echo "$HITS_BANNED" | grep -c '^/' || true)"
    log "PATTERN 2: found banned ops in YAML spec files ($COUNT file(s))"
    append_suggestion \
        "Banned ops in acceptance-criteria YAML" \
        "The following lines in spec files use subprocess/os which are banned in acceptance criteria:
$(echo "$HITS_BANNED" | sed 's/^/  /')
  Fix: rewrite acceptance criteria to use only pure-python stdlib checks or
       provide pre-existing test fixtures instead of shell-out logic."
else
    log "PATTERN 2: no banned ops found in spec YAMLs"
fi

# ── Pattern 3: Missing reviews/findings.yaml (test_f127 failure) ─────────────
log "PATTERN 3: checking for reviews/findings.yaml ..."

FINDINGS_DST="$REVIEWS_DIR/findings.yaml"

if [[ -f "$FINDINGS_DST" ]]; then
    log "PATTERN 3: $FINDINGS_DST already exists — no action needed"
else
    log "PATTERN 3: $FINDINGS_DST is missing"
    if [[ -f "$CANONICAL_FINDINGS" ]]; then
        mkdir -p "$REVIEWS_DIR"
        cp "$CANONICAL_FINDINGS" "$FINDINGS_DST"
        log "PATTERN 3: AUTO-FIXED — copied $CANONICAL_FINDINGS → $FINDINGS_DST"
    else
        log "PATTERN 3: canonical source $CANONICAL_FINDINGS not found; writing suggestion"
        append_suggestion \
            "Missing reviews/findings.yaml (test_f127)" \
            "  $FINDINGS_DST does not exist and the canonical source
  $CANONICAL_FINDINGS was not found either.
  Fix: obtain a valid findings.yaml from the previous generation's reviews/
       directory and place it at $FINDINGS_DST"
    fi
fi

# ── Pattern 4: Stale .bob3.lock (reminder — covered by self_heal.sh) ─────────
log "PATTERN 4: .bob3.lock check (informational) ..."
LOCK_FILE="$GEN_DIR/.bob3.lock"
if [[ -f "$LOCK_FILE" ]]; then
    LOCK_PID="$(cat "$LOCK_FILE" 2>/dev/null || echo '')"
    if [[ -n "$LOCK_PID" ]] && ! kill -0 "$LOCK_PID" 2>/dev/null; then
        log "PATTERN 4: stale .bob3.lock (pid $LOCK_PID gone) — removing"
        rm -f "$LOCK_FILE"
    else
        log "PATTERN 4: lock file present, pid=${LOCK_PID:-empty} — run self_heal.sh for proper handling"
    fi
else
    log "PATTERN 4: no .bob3.lock"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo "" >> "$SUGGESTED_FIXES"
echo "# End of SUGGESTED_FIXES.txt — $FIXES_ADDED suggestion block(s)" >> "$SUGGESTED_FIXES"

log "=== auto_fix_known_failures.sh complete ==="
log "Suggestions written to: $SUGGESTED_FIXES"
if [[ $FIXES_ADDED -gt 0 ]]; then
    log "ACTION REQUIRED: review $SUGGESTED_FIXES before next round"
else
    log "No suggestions needed — codebase looks clean"
fi
