"""Top-level run_loop entry point — re-exports from bob3.run_loop.

The AC 'File exists: src/run_loop.py' requires this file to exist at the
workspace root src/ directory. The canonical implementation lives in
src/bob3/run_loop.py; this module re-exports the public interface so that
both import paths resolve to the same code.
"""

from __future__ import annotations

from bob3.run_loop import (
    backstop_reap_orphan_subagents,
    backstop_reaper,
    claim_feature_as_executing,
    claim_feature_executing,
    claim_first_feature_before_batch_building,
    classify_evaluator_mcp_transient,
    classify_mcp_transient,
    classify_mcp_transient_error,
    classify_subagent_startup_crash,
    compute_persisted_artifact_count,
    create_subagent_watchdog,
    disk_reconciler_promotion_check,
    disk_reconciler_verify_fail_check,
    drain_mcp_transient_summary,
    handle_feature_terminal_state,
    handle_pending_successor_verify,
    handle_terminal_transition,
    load_exemption_sidecar,
    orphan_subagent_sweeper,
    ProjectMetadataCheckResult,
    rca_auto_reset_on_verification_failure,
    reap_subagent,
    reap_subagent_on_terminal,
    reap_subagent_on_terminal_state,
    reap_subagent_on_terminal_transition,
    reap_subagent_process,
    seed_readiness_at_iteration_start,
    seed_readiness_zero_features,
    set_pending_successor_verify,
    sigkill_orphan_subagents_sweeper,
    sigterm_subagent_on_terminal_state,
    sigterm_subagent_on_terminal_transition,
    sigterm_subagent_process,
    sweep_orphan_subagents,
    terminal_state_reaper,
    verify_project_metadata,
)

__all__ = [
    "backstop_reap_orphan_subagents",
    "backstop_reaper",
    "claim_feature_as_executing",
    "claim_feature_executing",
    "claim_first_feature_before_batch_building",
    "classify_evaluator_mcp_transient",
    "classify_mcp_transient",
    "classify_mcp_transient_error",
    "classify_subagent_startup_crash",
    "compute_persisted_artifact_count",
    "create_subagent_watchdog",
    "disk_reconciler_promotion_check",
    "disk_reconciler_verify_fail_check",
    "drain_mcp_transient_summary",
    "handle_feature_terminal_state",
    "handle_pending_successor_verify",
    "handle_terminal_transition",
    "load_exemption_sidecar",
    "orphan_subagent_sweeper",
    "ProjectMetadataCheckResult",
    "rca_auto_reset_on_verification_failure",
    "reap_subagent",
    "reap_subagent_on_terminal",
    "reap_subagent_on_terminal_state",
    "reap_subagent_on_terminal_transition",
    "reap_subagent_process",
    "seed_readiness_at_iteration_start",
    "seed_readiness_zero_features",
    "set_pending_successor_verify",
    "sigkill_orphan_subagents_sweeper",
    "sigterm_subagent_on_terminal_state",
    "sigterm_subagent_on_terminal_transition",
    "sigterm_subagent_process",
    "sweep_orphan_subagents",
    "terminal_state_reaper",
    "verify_project_metadata",
]
