"""Failing test for AC-12: pytest: tests/test_contract_grammar_blame_attribution.py

This file is generated by the test-writer sub-agent before the
implementer fires.  It must FAIL before implementation and PASS
after a correct implementation.

AC (verbatim): pytest: tests/test_contract_grammar_blame_attribution.py
Feature-ID:    73879589-55cc-4834-8a6b-7ebfb5a4bb17
AC-ID:         ac_12_pytest_tests_test_contract_grammar_blame
"""

from __future__ import annotations

import subprocess
import sys

import pytest


class TestAc12PytestTestsTestContractGrammarBlame:
    """Acceptance criterion: pytest: tests/test_contract_grammar_blame_attribution.py"""

    def test_blame_attribution_test_file_passes(self):
        result = subprocess.run(
            [sys.executable, "-m", "pytest", "tests/test_contract_grammar_blame_attribution.py", "-v", "--tb=short"],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, (
            f"tests/test_contract_grammar_blame_attribution.py failed:\n{result.stdout}\n{result.stderr}"
        )

    def test_pre_violation_blames_caller(self):
        from bob.spec_quality.contract_grammar import attribute_blame, BlameTarget
        blame = attribute_blame(violation_type="pre")
        assert blame == BlameTarget.CALLER

    def test_post_violation_blames_implementer(self):
        from bob.spec_quality.contract_grammar import attribute_blame, BlameTarget
        blame = attribute_blame(violation_type="post")
        assert blame == BlameTarget.IMPLEMENTER

    def test_inv_violation_blames_implementer(self):
        from bob.spec_quality.contract_grammar import attribute_blame, BlameTarget
        blame = attribute_blame(violation_type="inv")
        assert blame == BlameTarget.IMPLEMENTER
